// HOME
export const CHANGE_PROGRESS_MODE = 'CHANGE_PROGRESS_MODE';

// PROFILES
export const PROFILES_FORCE_UPDATE = 'PROFILES_FORCE_UPDATE';

export const NEW_PROFILE_MANAGE = 'NEW_PROFILE_MANAGE';
export const NEW_PROFILE_FETCHING = 'NEW_PROFILE_FETCHING';
export const NEW_PROFILE_FETCHED = 'NEW_PROFILE_FETCHED';
export const NEW_PROFILE_FETCH_FAILED = 'NEW_PROFILE_FETCH_FAILED';

export const GET_ALL_PROFILES_FETCHING = 'GET_ALL_PROFILES_FETCHING';
export const GET_ALL_PROFILES_FETCHED = 'GET_ALL_PROFILES_FETCHED';
export const GET_ALL_PROFILES_FAILED = 'GET_ALL_PROFILES_FAILED';

export const REMOVE_PROFILE_FETCHING = 'REMOVE_PROFILE_FETCHING';
export const REMOVE_PROFILE_FETCHED = 'REMOVE_PROFILE_FETCHED';
export const REMOVE_PROFILE_FAILED = 'REMOVE_PROFILE_FAILED';

export const SET_ERROR_OF_PROFILE_FORM = 'SET_ERROR_OF_PROFILE_FORM';
export const SELECT_DATA_SOURCE = 'SELECT_DATA_SOURCE';

//Progress
export const SEND_AUTHORS_NAMES_TO_PROGRESS = 'SEND_AUTHORS_NAMES_TO_PROGRESS';
export const SEND_FULL_AUTHORS_DATA_TO_PROGRESS = 'SEND_FULL_AUTHORS_DATA_TO_PROGRESS';
export const STOP_SCRAPING = 'STOP_SCRAPING';
export const START_SCRAPING_AUTHORS = 'START_SCRAPING_AUTHORS';
export const FILTER_AUTHORS_DATA = 'FILTER_AUTHORS_DATA';
export const START_NEXT_SCRAPING_AUTHORS = 'START_NEXT_SCRAPING_AUTHORS';

export const NEW_AUTHORS_TO_SERVER_SAVING = 'NEW_AUTHORS_TO_SERVER_SAVING';
export const ONE_AUTHOR_TO_SERVER_SAVING = 'ONE_AUTHOR_TO_SERVER_SAVING';
export const NEW_AUTOR_TO_SERVER_SAVED = 'NEW_AUTOR_SAVED_TO_SERVER';

//progress theme
export const SAVE_THEMES_STAGE_Y_TO_RES_Z = 'SAVE_X_STAGE_Y_TO_RES_Z';
export const SET_PROGRESS_THEMES_DATA = 'SET_PROGRESS_THEMES_DATA';

//COLLECTED_DATA
export const SAVE_COLLECTED_THEMES_BY_KEY = 'SAVE_COLLECTED_THEMES_BY_KEY';
export const DELETE_COLLECTED_THEMES_BY_KEY = 'DELETE_COLLECTED_THEMES_BY_KEY';

export const COLLECTED_DATA_FETCHING = 'COLLECTED_DATA_FETCHING';
export const COLLECTED_DATA_FETCHED = 'COLLECTED_DATA_FETCHED';
export const COLLECTED_DATA_FETCH_FAILED = 'COLLECTED_DATA_FETCH_FAILED';

export const ALL_AUTHORS_FROM_SERVER_FETCHING = 'ALL_AUTHORS_FROM_SERVER_FETCHING';
export const ALL_AUTHORS_FROM_SERVER_FETCHED = 'ALL_AUTHORS_FROM_SERVER_FETCHED';
export const ALL_AUTHORS_FROM_SERVER_FAILED = 'ALL_AUTHORS_FROM_SERVER_FAILED';